sudo: required
services:
  - docker
language:
  - c
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
osx:
  - osx_image: xcode8.1
addons:
  apt:
    packages:
    - flex
    - bison
    - gperf
    - pkg-config
    - clang
    - binutils-mingw-w64-i686
    - gcc-mingw-w64-i686
    - binutils-mingw-w64
    - gcc-mingw-w64
env:
  global:
    - BUILD_BRANCH=$TRAVIS_BRANCH
    - BUILD_ID=$TRAVIS_BUILD_NUMBER
    - PACKAGE_NAME=openaaa
  matrix:
    - BUILD_DEPLOY=1 BUILD_TARGET=linux PACK=none
    - BUILD_DEPLOY=1 BUILD_TARGET=osx PACK=none
    - BUILD_DEPLOY=1 BUILD_TARGET=win32 PACK=none
    - BUILD_DEPLOY=1 BUILD_TARGET=win64 PACK=none
    - BUILD_DEPLOY=1 BUILD_TARGET=linux OS=el DIST=6 PACK=rpm
    - BUILD_DEPLOY=1 BUILD_TARGET=linux OS=el DIST=7 PACK=rpm
    - BUILD_DEPLOY=1 BUILD_TARGET=linux OS=fedora DIST=24 PACK=rpm
    - BUILD_DEPLOY=1 BUILD_TARGET=linux OS=fedora DIST=25 PACK=rpm
    - BUILD_DEPLOY=1 BUILD_TARGET=linux OS=ubuntu DIST=trusty PACK=deb
    - BUILD_DEPLOY=1 BUILD_TARGET=linux OS=ubuntu DIST=precise PACK=deb
    - BUILD_DEPLOY=1 BUILD_TARGET=linux OS=ubuntu DIST=xenial PACK=deb
    - BUILD_DEPLOY=1 BUILD_TARGET=linux OS=debian DIST=jessie PACK=deb
    - BUILD_DEPLOY=1 BUILD_TARGET=linux OS=debian DIST=wheezy PACK=deb
    - BUILD_DEPLOY=1 BUILD_TARGET=linux OS=debian DIST=stretch PACK=deb
    - BUILD_DEPLOY=1 BUILD_TARGET=linux OS=debian DIST=sid PACK=deb
matrix:
  allow_failures:
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=el DIST=6 PACK=rpm
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=el DIST=7 PACK=rpm
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=fedora DIST=24 PACK=rpm
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=fedora DIST=25 PACK=rpm
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=ubuntu DIST=precise PACK=deb
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=ubuntu DIST=trusty PACK=deb
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=ubuntu DIST=xenial PACK=deb
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=debian DIST=jessie PACK=deb
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=debian DIST=wheezy PACK=deb
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=debian DIST=stretch PACK=deb
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=debian DIST=sid PACK=deb
  exclude:
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=el DIST=6 PACK=rpm
      compiler: clang
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=el DIST=7 PACK=rpm
      compiler: clang
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=fedora DIST=24 PACK=rpm
      compiler: clang
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=fedora DIST=25 PACK=rpm
      compiler: clang
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=ubuntu DIST=precise PACK=deb
      compiler: clang
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=ubuntu DIST=trusty PACK=deb
      compiler: clang
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=ubuntu DIST=xenial PACK=deb
      compiler: clang
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=debian DIST=wheezy PACK=deb
      compiler: clang
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=debian DIST=jessie PACK=deb
      compiler: clang
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=debian DIST=stretch PACK=deb
      compiler: clang
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=debian DIST=sid PACK=deb
      compiler: clang
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=el DIST=6 PACK=rpm
      os: osx
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=el DIST=7 PACK=rpm
      os: osx
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=fedora DIST=24 PACK=rpm
      os: osx
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=fedora DIST=25 PACK=rpm
      os: osx
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=ubuntu DIST=precise PACK=deb
      os: osx
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=ubuntu DIST=trusty PACK=deb
      os: osx
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=ubuntu DIST=xenial PACK=deb
      os: osx
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=debian DIST=wheezy PACK=deb
      os: osx
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=debian DIST=jessie PACK=deb
      os: osx
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=debian DIST=stretch PACK=deb
      os: osx
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=debian DIST=sid PACK=deb
      os: osx
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux PACK=none
      os: osx
    - env: BUILD_DEPLOY=1 BUILD_TARGET=osx PACK=none
      os: linux
    - env: BUILD_DEPLOY=1 BUILD_TARGET=win32 PACK=none
      os: osx
    - env: BUILD_DEPLOY=1 BUILD_TARGET=win64 PACK=none 
      os: osx
    - env: BUILD_DEPLOY=1 BUILD_TARGET=win32 PACK=none
      compiler: clang
    - env: BUILD_DEPLOY=1 BUILD_TARGET=win64 PACK=none
      compiler: clang
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=el DIST=6 PACK=rpm
      osx_image: xcode7.1
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=el DIST=7 PACK=rpm
      osx_image: xcode7.1
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=fedora DIST=24 PACK=rpm
      osx_image: xcode7.1
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=fedora DIST=25 PACK=rpm
      osx_image: xcode7.1
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=ubuntu DIST=precise PACK=deb
      osx_image: xcode7.1
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=ubuntu DIST=trusty PACK=deb
      osx_image: xcode7.1
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=ubuntu DIST=xenial PACK=deb
      osx_image: xcode7.1
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=debian DIST=wheezy PACK=deb
      osx_image: xcode7.1
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=debian DIST=jessie PACK=deb
      osx_image: xcode7.1
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=debian DIST=stretch PACK=deb
      osx_image: xcode7.1
    - env: BUILD_DEPLOY=1 BUILD_TARGET=linux OS=debian DIST=sid PACK=deb
      osx_image: xcode7.1
before_deploy:
- export
- export BUILD_ARCHIVE=openaaa-$BUILD_MAJOR.$BUILD_MINOR.$BUILD_REVISION-$BUILD_OS_NAME-$BUILD_OS_ARCH-$BUILD_OS_RELEASE.tar.gz
before_install:
- source ./scripts/travis/before_install.sh
- gem install package_cloud
script:
- export
- shell_session_update() { :; } # workarround mac os build bug
# mkdir ./rpm
# cp ./scripts/package/openaaa.spec ./rpm/ 
- git submodule update --init --recursive
- git describe --long --always
- git clone https://github.com/packpack/packpack.git packpack
- 'if [[ $PACK == "none" ]]; then 
    make defconfig ;
    make ;
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      sudo make modules_install INSTALL_PATH=/opt/aaa ;
    else
      sudo make modules_install ;
    fi
  else
    packpack/packpack; 
  fi'
deploy:
  # Deploy packages to PackageCloud
  provider: packagecloud
  username: ${PACKAGECLOUD_USER}
  repository: ${PACKAGECLOUD_REPO}
  token: ${PACKAGECLOUD_TOKEN}
  dist: ${OS}/${DIST}
  package_glob: build/*.{deb,rpm}
  skip_cleanup: true
  on:
    tags: true
#    branch: master
    condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
notifications:
  on_success: never
  on_failure: never
  email: false
